/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lsp;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Naufal
 */
public class Admin extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModelSiswa,tabModelPetugas,tabModelKelas,tabModelSpp,tabModelTransaksi, tabModelLaporan;
    Connection cn = koneksi.con();
    String nama;

    /**
     * Creates new form Dashboard
     */
    public Admin(String nama) {
        initComponents();
        welcometxt.setText("Selamat Datang, " + nama);
        this.nama = nama;
        idSiswa.setEnabled(false);
        idPetugas.setEnabled(false);
        idKelas.setEnabled(false);
        idSpp.setEnabled(false);
        idTransaksi.setEnabled(false);
        judulSiswa();
        tampilDataSiswa("");
        judulPetugas();
        tampilDataPetugas("");
        judulKelas();
        tampilDataKelas("");
        judulSpp();
        tampilDataSpp("");
        judulTransaksi();
        tampilDataTransaksi("");
        
    }
    
    // Data Siswa
    
    public void judulSiswa() {
        Object[] judul = {
            "ID", "Nis" , "Nama", "ID Kelas", "Alamat", "No Telp","ID SPP"
        };
        tabModelSiswa = new DefaultTableModel (null, judul);
        tableSiswa.setModel(tabModelSiswa);
    }
    
    public void tampilDataSiswa(String where) {
          try {
              st = cn.createStatement();
              tabModelSiswa.getDataVector().removeAllElements();
              tabModelSiswa.fireTableDataChanged();
              rs = st.executeQuery("SELECT * FROM siswa " + where);
              
          while (rs.next()) {
              Object[] data = {
              rs.getString("id"),
              rs.getString("nis"),
              rs.getString("nama"),
              rs.getString("id_kelas"),
              rs.getString("alamat"),
              rs.getString("no_telp"),
              rs.getString("id_spp"),
          };
          
            tabModelSiswa.addRow(data);
          } 
        } catch(Exception e) {
         e.printStackTrace();
        }
      }
    
    public void resetSiswa () {
        idSiswa.setText("");
        nisSiswa.setText("");
        namaSiswa.setText("");
        idKelasSiswa.setText("");
        alamatSiswa.setText("");
        noTelpSiswa.setText("");
        idSppSiswa.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JPanel();
        welcometxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Siswa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        TambahbtnSiswa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idSiswa = new javax.swing.JTextField();
        DeletebtnSiswa = new javax.swing.JButton();
        UpdatebtnSiswa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nisSiswa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        namaSiswa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idKelasSiswa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alamatSiswa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noTelpSiswa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        idSppSiswa = new javax.swing.JTextField();
        RefreshbtnSiswa = new javax.swing.JButton();
        Petugas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePetugas = new javax.swing.JTable();
        tambahPetugasbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idPetugas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        usernamePetugas = new javax.swing.JTextField();
        namaPetugas = new javax.swing.JTextField();
        levelPetugas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DeletebtnPetugas = new javax.swing.JButton();
        UpdatebtnPetugas = new javax.swing.JButton();
        RefreshbtnPetugas = new javax.swing.JButton();
        Kelas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKelas = new javax.swing.JTable();
        tambahKelasbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        idKelas = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        namaKelas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        kompetensiKelas = new javax.swing.JTextField();
        DeletebtnKelas = new javax.swing.JButton();
        UpdatebtnKelas = new javax.swing.JButton();
        RefreshbtnKelas = new javax.swing.JButton();
        Spp = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSpp = new javax.swing.JTable();
        tambahSppbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        idSpp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tahunSpp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nominalSpp = new javax.swing.JTextField();
        DeletebtnSpp = new javax.swing.JButton();
        UpdatebtnSpp = new javax.swing.JButton();
        RefreshbtnSpp = new javax.swing.JButton();
        Laporan = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        idTransaksi = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        idPetugasTransaksi = new javax.swing.JTextField();
        idSIswaTransaksi = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tanggalBayar = new javax.swing.JTextField();
        bulanBayar = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tahunBayar = new javax.swing.JTextField();
        idSppTransaksi = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jumlahBayar = new javax.swing.JTextField();
        tambahDataTransaksi = new javax.swing.JButton();
        DeletebtnTransaksi = new javax.swing.JButton();
        UpdatebtnTransaksi = new javax.swing.JButton();
        RefreshbtnTransaksi = new javax.swing.JButton();
        Transaksi = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableLaporan = new javax.swing.JTable();
        Printbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcometxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcometxt.setText("Selamat Datang, ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Di Aplikasi SPP");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcometxt)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)))
                .addContainerGap(590, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(welcometxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard", Dashboard);

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nis", "Nama", "ID Kelas", "Alamat", "No Telp", "ID SPP"
            }
        ));
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSiswa);

        TambahbtnSiswa.setText("Tambah Data");
        TambahbtnSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahbtnSiswaActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        DeletebtnSiswa.setText("Delete");
        DeletebtnSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnSiswaActionPerformed(evt);
            }
        });

        UpdatebtnSiswa.setText("Update");
        UpdatebtnSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnSiswaActionPerformed(evt);
            }
        });

        jLabel4.setText("Nis");

        jLabel5.setText("Nama");

        jLabel6.setText("ID Kelas");

        jLabel7.setText("Alamat");

        jLabel8.setText("No Telp");

        jLabel9.setText("ID SPP");

        RefreshbtnSiswa.setText("Refresh");
        RefreshbtnSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnSiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SiswaLayout = new javax.swing.GroupLayout(Siswa);
        Siswa.setLayout(SiswaLayout);
        SiswaLayout.setHorizontalGroup(
            SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SiswaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TambahbtnSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SiswaLayout.createSequentialGroup()
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SiswaLayout.createSequentialGroup()
                                .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(14, 14, 14)
                                .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nisSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idKelasSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamatSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noTelpSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idSppSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SiswaLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(DeletebtnSiswa)
                                .addGap(18, 18, 18)
                                .addComponent(UpdatebtnSiswa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RefreshbtnSiswa)))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SiswaLayout.setVerticalGroup(
            SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiswaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SiswaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(SiswaLayout.createSequentialGroup()
                        .addComponent(TambahbtnSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nisSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idKelasSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alamatSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noTelpSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idSppSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeletebtnSiswa)
                            .addComponent(UpdatebtnSiswa)
                            .addComponent(RefreshbtnSiswa))
                        .addGap(61, 61, 61))))
        );

        jTabbedPane1.addTab("Data Siswa", Siswa);

        tablePetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Nama", "Level"
            }
        ));
        tablePetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePetugasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePetugas);

        tambahPetugasbtn.setText("Tambah Data");
        tambahPetugasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPetugasbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("ID ");

        jLabel10.setText("Username");

        jLabel13.setText("Nama");

        jLabel14.setText("Level");

        DeletebtnPetugas.setText("Delete");
        DeletebtnPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnPetugasActionPerformed(evt);
            }
        });

        UpdatebtnPetugas.setText("Update");
        UpdatebtnPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnPetugasActionPerformed(evt);
            }
        });

        RefreshbtnPetugas.setText("Refresh");
        RefreshbtnPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnPetugasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PetugasLayout = new javax.swing.GroupLayout(Petugas);
        Petugas.setLayout(PetugasLayout);
        PetugasLayout.setHorizontalGroup(
            PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetugasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PetugasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tambahPetugasbtn))
                    .addGroup(PetugasLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PetugasLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernamePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(levelPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PetugasLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(DeletebtnPetugas)
                                .addGap(18, 18, 18)
                                .addComponent(UpdatebtnPetugas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RefreshbtnPetugas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PetugasLayout.setVerticalGroup(
            PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PetugasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PetugasLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(PetugasLayout.createSequentialGroup()
                        .addComponent(tambahPetugasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernamePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeletebtnPetugas)
                            .addComponent(UpdatebtnPetugas)
                            .addComponent(RefreshbtnPetugas))
                        .addGap(99, 99, 99))))
        );

        jTabbedPane1.addTab("Data Petugas", Petugas);

        tableKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama", "Kompetensi"
            }
        ));
        tableKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKelasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableKelas);

        tambahKelasbtn.setText("Tambah Data");
        tambahKelasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKelasbtnActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        jLabel12.setText("Nama");

        jLabel15.setText("Kompetensi");

        DeletebtnKelas.setText("Delete");
        DeletebtnKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnKelasActionPerformed(evt);
            }
        });

        UpdatebtnKelas.setText("Update");
        UpdatebtnKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnKelasActionPerformed(evt);
            }
        });

        RefreshbtnKelas.setText("Refresh");
        RefreshbtnKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KelasLayout = new javax.swing.GroupLayout(Kelas);
        Kelas.setLayout(KelasLayout);
        KelasLayout.setHorizontalGroup(
            KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KelasLayout.createSequentialGroup()
                        .addGroup(KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KelasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tambahKelasbtn))
                            .addGroup(KelasLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(KelasLayout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(namaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(KelasLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(idKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(KelasLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(kompetensiKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(DeletebtnKelas)
                        .addGap(18, 18, 18)
                        .addComponent(UpdatebtnKelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RefreshbtnKelas)
                        .addGap(80, 80, 80))))
        );
        KelasLayout.setVerticalGroup(
            KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelasLayout.createSequentialGroup()
                .addGroup(KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KelasLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KelasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tambahKelasbtn)
                        .addGap(56, 56, 56)
                        .addGroup(KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(idKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(namaKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(kompetensiKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeletebtnKelas)
                            .addComponent(UpdatebtnKelas)
                            .addComponent(RefreshbtnKelas))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Kelas", Kelas);

        tableSpp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tahun", "Nominal"
            }
        ));
        tableSpp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSppMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableSpp);

        tambahSppbtn.setText("Tambah Data");
        tambahSppbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahSppbtnActionPerformed(evt);
            }
        });

        jLabel16.setText("ID");

        jLabel17.setText("Tahun");

        jLabel18.setText("Nominal");

        DeletebtnSpp.setText("Delete");
        DeletebtnSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnSppActionPerformed(evt);
            }
        });

        UpdatebtnSpp.setText("Update");
        UpdatebtnSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnSppActionPerformed(evt);
            }
        });

        RefreshbtnSpp.setText("Refresh");
        RefreshbtnSpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnSppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SppLayout = new javax.swing.GroupLayout(Spp);
        Spp.setLayout(SppLayout);
        SppLayout.setHorizontalGroup(
            SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SppLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambahSppbtn))
                    .addGroup(SppLayout.createSequentialGroup()
                        .addGroup(SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SppLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(SppLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tahunSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SppLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(idSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SppLayout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nominalSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(SppLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(DeletebtnSpp)
                                .addGap(18, 18, 18)
                                .addComponent(UpdatebtnSpp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RefreshbtnSpp)))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SppLayout.setVerticalGroup(
            SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SppLayout.createSequentialGroup()
                .addGroup(SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SppLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SppLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tambahSppbtn)
                        .addGap(53, 53, 53)
                        .addGroup(SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(idSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tahunSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(nominalSpp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(SppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeletebtnSpp)
                            .addComponent(UpdatebtnSpp)
                            .addComponent(RefreshbtnSpp))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data SPP", Spp);

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Petugas", "ID Siswa", "Tanggal Bayar", "Bulan Bayar", "Tahun Bayar", "ID Spp", "Jumlah Bayar"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableTransaksi);

        jLabel27.setText("ID");

        jLabel28.setText("ID Petugas");

        jLabel29.setText("ID Siswa");

        jLabel30.setText("Tanggal Bayar");

        jLabel31.setText("Bulan Bayar");

        jLabel32.setText("Tahun Bayar");

        jLabel33.setText("ID SPP");

        jLabel34.setText("Jumlah Bayar");

        tambahDataTransaksi.setText("Tambah Data");
        tambahDataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataTransaksiActionPerformed(evt);
            }
        });

        DeletebtnTransaksi.setText("Delete");
        DeletebtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnTransaksiActionPerformed(evt);
            }
        });

        UpdatebtnTransaksi.setText("Update");
        UpdatebtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnTransaksiActionPerformed(evt);
            }
        });

        RefreshbtnTransaksi.setText("Refresh");
        RefreshbtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LaporanLayout = new javax.swing.GroupLayout(Laporan);
        Laporan.setLayout(LaporanLayout);
        LaporanLayout.setHorizontalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LaporanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tambahDataTransaksi))
                    .addGroup(LaporanLayout.createSequentialGroup()
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LaporanLayout.createSequentialGroup()
                                .addComponent(DeletebtnTransaksi)
                                .addGap(18, 18, 18)
                                .addComponent(UpdatebtnTransaksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RefreshbtnTransaksi))
                            .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LaporanLayout.createSequentialGroup()
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LaporanLayout.createSequentialGroup()
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(idPetugasTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LaporanLayout.createSequentialGroup()
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(idSIswaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LaporanLayout.createSequentialGroup()
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tanggalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LaporanLayout.createSequentialGroup()
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bulanBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LaporanLayout.createSequentialGroup()
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tahunBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LaporanLayout.createSequentialGroup()
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(idSppTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(LaporanLayout.createSequentialGroup()
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LaporanLayout.setVerticalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaporanLayout.createSequentialGroup()
                .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LaporanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tambahDataTransaksi)
                        .addGap(25, 25, 25)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(idTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(idPetugasTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(idSIswaTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tanggalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(bulanBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(tahunBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(idSppTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeletebtnTransaksi)
                            .addComponent(UpdatebtnTransaksi)
                            .addComponent(RefreshbtnTransaksi)))
                    .addGroup(LaporanLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transaksi", Laporan);

        tableLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID Petugas", "ID Siswa", "Tanggal Bayar", "Bulan Bayar", "Tahun Bayar", "ID Spp", "Jumlah Bayar"
            }
        ));
        jScrollPane5.setViewportView(tableLaporan);

        Printbtn.setText("Print");
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TransaksiLayout = new javax.swing.GroupLayout(Transaksi);
        Transaksi.setLayout(TransaksiLayout);
        TransaksiLayout.setHorizontalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(Printbtn)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        TransaksiLayout.setVerticalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransaksiLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TransaksiLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Printbtn)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Laporan", Transaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdatebtnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnSiswaActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("UPDATE siswa set " 
            +"nis='"          +nisSiswa.getText() + "', "
            +"nama='"          +namaSiswa.getText() + "', "
            +"id_kelas='"          +idKelasSiswa.getText() + "', "
            +"alamat='"          + alamatSiswa.getText() + "', "
            +"no_telp='"          +noTelpSiswa.getText() + "', "
            +"id_spp='"          +idSppSiswa.getText() + "'"
            + " where " + "id='"+idSiswa.getText()+"'");
            tampilDataSiswa("");
                JOptionPane.showMessageDialog(null, "Update Berhasil");
            resetSiswa();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdatebtnSiswaActionPerformed

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        idSiswa.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(), 0).toString());
        nisSiswa.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(), 1).toString());
        namaSiswa.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(), 2).toString());
        idKelasSiswa.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(), 3).toString());
        alamatSiswa.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(), 4).toString());
        noTelpSiswa.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(), 5).toString());
        idSppSiswa.setText(tableSiswa.getValueAt(tableSiswa.getSelectedRow(), 6).toString());
        
        DeletebtnSiswa.setEnabled(true);
        UpdatebtnSiswa.setEnabled(true);
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void DeletebtnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnSiswaActionPerformed
        try{
            int jawab;

            if ((jawab = JOptionPane.showConfirmDialog(null, "ingin menghapus data?","Konfirmasi",JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM siswa WHERE id='"
                    + tabModelSiswa.getValueAt(tableSiswa.getSelectedRow(), 0) + "'");
                tampilDataSiswa("");
                resetSiswa();
            }
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DeletebtnSiswaActionPerformed

    private void TambahbtnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahbtnSiswaActionPerformed
        tambahSiswa ts = new tambahSiswa();
        ts.setVisible(true);
    }//GEN-LAST:event_TambahbtnSiswaActionPerformed

    private void RefreshbtnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnSiswaActionPerformed
        tampilDataSiswa("");
    }//GEN-LAST:event_RefreshbtnSiswaActionPerformed

     // Petugas
    public void judulPetugas() {
        Object[] judul = {
            "ID", "Username" , "Nama", "Level"
        };
        tabModelPetugas = new DefaultTableModel (null, judul);
        tablePetugas.setModel(tabModelPetugas);
    }
    
    public void tampilDataPetugas(String where) {
          try {
              st = cn.createStatement();
              tabModelPetugas.getDataVector().removeAllElements();
              tabModelPetugas.fireTableDataChanged();
              rs = st.executeQuery("SELECT * FROM petugas " + where);
              
          while (rs.next()) {
              Object[] data = {
              rs.getString("id"),
              rs.getString("username"),
              rs.getString("nama"),
              rs.getString("level"),
          };
          
            tabModelPetugas.addRow(data);
          } 
        } catch(Exception e) {
         e.printStackTrace();
        }
    }
    
    public void resetPetugas() {
        idPetugas.setText("");
        usernamePetugas.setText("");
        namaPetugas.setText("");
        levelPetugas.setText("");
    }
    
    private void tablePetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePetugasMouseClicked
        idPetugas.setText(tablePetugas.getValueAt(tablePetugas.getSelectedRow(), 0).toString());
        usernamePetugas.setText(tablePetugas.getValueAt(tablePetugas.getSelectedRow(), 1).toString());
        namaPetugas.setText(tablePetugas.getValueAt(tablePetugas.getSelectedRow(), 2).toString());
        levelPetugas.setText(tablePetugas.getValueAt(tablePetugas.getSelectedRow(), 3).toString());
        
        DeletebtnPetugas.setEnabled(true);
        UpdatebtnPetugas.setEnabled(true);
    }//GEN-LAST:event_tablePetugasMouseClicked

    private void DeletebtnPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnPetugasActionPerformed
        try{
            int jawab;

            if ((jawab = JOptionPane.showConfirmDialog(null, "ingin menghapus data?","Konfirmasi",JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM petugas WHERE id='"
                    + tabModelPetugas.getValueAt(tablePetugas.getSelectedRow(), 0) + "'");
                tampilDataPetugas("");
                resetPetugas();
            }
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DeletebtnPetugasActionPerformed

    private void UpdatebtnPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnPetugasActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("UPDATE petugas set " 
            +"username='"          +usernamePetugas.getText() + "', "
            +"nama='"          +namaPetugas.getText() + "', "
            +"level='"          +levelPetugas.getText() + "'"
            + " where " + "id='"+idPetugas.getText()+"'");
            tampilDataPetugas("");
                JOptionPane.showMessageDialog(null, "Update Berhasil");
            resetPetugas();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdatebtnPetugasActionPerformed

    private void RefreshbtnPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnPetugasActionPerformed
        tampilDataPetugas("");
    }//GEN-LAST:event_RefreshbtnPetugasActionPerformed

    private void tambahPetugasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPetugasbtnActionPerformed
        tambahPetugas tp = new tambahPetugas();
        tp.setVisible(true);
    }//GEN-LAST:event_tambahPetugasbtnActionPerformed

    // Kelas
    
    public void judulKelas() {
        Object[] judul = {
            "ID", "Nama" , "Kompetensi"
        };
        tabModelKelas = new DefaultTableModel (null, judul);
        tableKelas.setModel(tabModelKelas);
    }
    
    public void tampilDataKelas(String where) {
          try {
              st = cn.createStatement();
              tabModelKelas.getDataVector().removeAllElements();
              tabModelKelas.fireTableDataChanged();
              rs = st.executeQuery("SELECT * FROM kelas " + where);
              
          while (rs.next()) {
              Object[] data = {
              rs.getString("id"),
              rs.getString("nama"),
              rs.getString("kompetensi"),
          };
          
            tabModelKelas.addRow(data);
          } 
        } catch(Exception e) {
         e.printStackTrace();
        }
      }
    
    public void resetKelas() {
        idKelas.setText("");
        namaKelas.setText("");
        kompetensiKelas.setText("");
    }
    
    private void DeletebtnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnKelasActionPerformed
        try{
            int jawab;

            if ((jawab = JOptionPane.showConfirmDialog(null, "ingin menghapus data?","Konfirmasi",JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM kelas WHERE id='"
                    + tabModelKelas.getValueAt(tableKelas.getSelectedRow(), 0) + "'");
                tampilDataKelas("");
                resetKelas();
            }
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DeletebtnKelasActionPerformed

    private void UpdatebtnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnKelasActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("UPDATE kelas set " 
            +"nama='"          +namaKelas.getText() + "', "
            +"kompetensi='"          +kompetensiKelas.getText() + " where " + "id='"+idKelas.getText()+"'");
            tampilDataKelas("");
                JOptionPane.showMessageDialog(null, "Update Berhasil");
            resetKelas();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdatebtnKelasActionPerformed

    private void RefreshbtnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnKelasActionPerformed
        tampilDataKelas("");
    }//GEN-LAST:event_RefreshbtnKelasActionPerformed

    private void tableKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKelasMouseClicked
        idKelas.setText(tableKelas.getValueAt(tableKelas.getSelectedRow(), 0).toString());
        namaKelas.setText(tableKelas.getValueAt(tableKelas.getSelectedRow(), 1).toString());
        kompetensiKelas.setText(tableKelas.getValueAt(tableKelas.getSelectedRow(), 2).toString());
        
        DeletebtnKelas.setEnabled(true);
        UpdatebtnKelas.setEnabled(true);
    }//GEN-LAST:event_tableKelasMouseClicked

    private void tambahKelasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKelasbtnActionPerformed
        tambahKelas tk = new tambahKelas();
        tk.setVisible(true);
    }//GEN-LAST:event_tambahKelasbtnActionPerformed

    // SPP
    
    public void judulSpp() {
        Object[] judul = {
            "ID", "Tahun" , "Nominal"
        };
        tabModelSpp = new DefaultTableModel (null, judul);
        tableSpp.setModel(tabModelSpp);
    }
    
    public void tampilDataSpp(String where) {
          try {
              st = cn.createStatement();
              tabModelSpp.getDataVector().removeAllElements();
              tabModelSpp.fireTableDataChanged();
              rs = st.executeQuery("SELECT * FROM spp " + where);
              
          while (rs.next()) {
              Object[] data = {
              rs.getString("id"),
              rs.getString("tahun"),
              rs.getString("nominal"),
          };
          
            tabModelSpp.addRow(data);
          } 
        } catch(Exception e) {
         e.printStackTrace();
        }
      }
    
    public void resetSpp() {
        idSpp.setText("");
        tahunSpp.setText("");
        nominalSpp.setText("");
    }
    
    
    private void DeletebtnSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnSppActionPerformed
        try{
            int jawab;

            if ((jawab = JOptionPane.showConfirmDialog(null, "ingin menghapus data?","Konfirmasi",JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM spp WHERE id='"
                    + tabModelSpp.getValueAt(tableSpp.getSelectedRow(), 0) + "'");
                tampilDataSpp("");
                resetSpp();
            }
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DeletebtnSppActionPerformed

    private void UpdatebtnSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnSppActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("UPDATE spp set " 
            +"tahun='"          +tahunSpp.getText() + "', "
            +"nominal='"          +nominalSpp.getText() + " where " + "id='"+idSpp.getText()+"'");;
            tampilDataSpp("");
                JOptionPane.showMessageDialog(null, "Update Berhasil");
            resetSpp();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdatebtnSppActionPerformed

    private void RefreshbtnSppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnSppActionPerformed
        tampilDataSpp("");
    }//GEN-LAST:event_RefreshbtnSppActionPerformed

    private void tableSppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSppMouseClicked
        idSpp.setText(tableSpp.getValueAt(tableSpp.getSelectedRow(), 0).toString());
        tahunSpp.setText(tableSpp.getValueAt(tableSpp.getSelectedRow(), 1).toString());
        nominalSpp.setText(tableSpp.getValueAt(tableSpp.getSelectedRow(), 2).toString());
        
        DeletebtnSpp.setEnabled(true);
        UpdatebtnSpp.setEnabled(true);
    }//GEN-LAST:event_tableSppMouseClicked

    private void tambahSppbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahSppbtnActionPerformed
        tambahSpp tsp = new tambahSpp();
        tsp.setVisible(true);
    }//GEN-LAST:event_tambahSppbtnActionPerformed

    // Transaksi
    
    public void judulTransaksi() {
        Object[] judul = {
            "ID", "ID Petugas" , "ID Siswa", "Tanggal bayar", "Bulan Bayar", "Tahun Bayar", "ID Spp", "Jumlah Bayar"
        };
        tabModelTransaksi = new DefaultTableModel (null, judul);
        tabModelLaporan = new DefaultTableModel (null, judul);
        tableTransaksi.setModel(tabModelTransaksi);
        tableLaporan.setModel(tabModelLaporan);
    }
    
    public void tampilDataTransaksi(String where) {
          try {
              st = cn.createStatement();
              tabModelTransaksi.getDataVector().removeAllElements();
              tabModelTransaksi.fireTableDataChanged();
              rs = st.executeQuery("SELECT * FROM pembayaran " + where);
              
          while (rs.next()) {
              Object[] data = {
              rs.getString("id"),
              rs.getString("id_petugas"),
              rs.getString("id_siswa"),
              rs.getString("tgl_bayar"),
              rs.getString("bulan_bayar"),
              rs.getString("tahun_bayar"),
              rs.getString("id_spp"),
              rs.getString("jumlah_bayar"),
          };
          
            tabModelTransaksi.addRow(data);
            tabModelLaporan.addRow(data);
          } 
        } catch(Exception e) {
         e.printStackTrace();
        }
      }
    
    public void resetTransaksi() {
        idTransaksi.setText("");
        idPetugasTransaksi.setText("");
        idSIswaTransaksi.setText("");
        tanggalBayar.setText("");
        bulanBayar.setText("");
        tahunBayar.setText("");
        idSppTransaksi.setText("");
        jumlahBayar.setText("");
    }
    
    private void DeletebtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnTransaksiActionPerformed
        try{
            int jawab;

            if ((jawab = JOptionPane.showConfirmDialog(null, "ingin menghapus data?","Konfirmasi",JOptionPane.YES_NO_OPTION)) == 0) {
                st = cn.createStatement();
                st.executeUpdate("DELETE FROM pembayaran WHERE id='"
                    + tabModelTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 0) + "'");
                tampilDataTransaksi("");
                resetTransaksi();
            }
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DeletebtnTransaksiActionPerformed

    private void UpdatebtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnTransaksiActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("UPDATE pembayaran set " 
            +"id_petugas='"          +idPetugasTransaksi.getText() + "', "
            +"id_siswa='"          +idSIswaTransaksi.getText() + "', "
            +"tgl_bayar='"          +tanggalBayar.getText() + "', "
            +"bulan_bayar='"          +bulanBayar.getText() + "', "
            +"tahun_bayar='"          +tahunBayar.getText() + "', "
            +"id_spp='"          +idSppTransaksi.getText() + "', "
            +"jumlah_bayar='"          +jumlahBayar.getText() + "', "
            +" where " + "id='"+idTransaksi.getText()+"'");
            tampilDataTransaksi("");
                JOptionPane.showMessageDialog(null, "Update Berhasil");
            resetTransaksi();
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdatebtnTransaksiActionPerformed

    private void RefreshbtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnTransaksiActionPerformed
        tampilDataTransaksi("");
    }//GEN-LAST:event_RefreshbtnTransaksiActionPerformed

    private void tambahDataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataTransaksiActionPerformed
        tambahTransaksi tt = new tambahTransaksi();
        tt.setVisible(true);
    }//GEN-LAST:event_tambahDataTransaksiActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        idTransaksi.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 0).toString());
        idPetugasTransaksi.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 1).toString());
        idSIswaTransaksi.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 2).toString());
        tanggalBayar.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 3).toString());
        bulanBayar.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 4).toString());
        tahunBayar.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 5).toString());
        idSppTransaksi.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 6).toString());
        jumlahBayar.setText(tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 7).toString());
        
        DeletebtnTransaksi.setEnabled(true);
        UpdatebtnTransaksi.setEnabled(true);
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
        try {
     if (! tableTransaksi.print()) {
         System.err.println("User cancelled printing");
     } 
 } catch (java.awt.print.PrinterException e) {
     System.err.format("Cannot print %s%n", e.getMessage()); 
 } 
    }//GEN-LAST:event_PrintbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton DeletebtnKelas;
    private javax.swing.JButton DeletebtnPetugas;
    private javax.swing.JButton DeletebtnSiswa;
    private javax.swing.JButton DeletebtnSpp;
    private javax.swing.JButton DeletebtnTransaksi;
    private javax.swing.JPanel Kelas;
    private javax.swing.JPanel Laporan;
    private javax.swing.JPanel Petugas;
    private javax.swing.JButton Printbtn;
    private javax.swing.JButton RefreshbtnKelas;
    private javax.swing.JButton RefreshbtnPetugas;
    private javax.swing.JButton RefreshbtnSiswa;
    private javax.swing.JButton RefreshbtnSpp;
    private javax.swing.JButton RefreshbtnTransaksi;
    private javax.swing.JPanel Siswa;
    private javax.swing.JPanel Spp;
    private javax.swing.JButton TambahbtnSiswa;
    private javax.swing.JPanel Transaksi;
    private javax.swing.JButton UpdatebtnKelas;
    private javax.swing.JButton UpdatebtnPetugas;
    private javax.swing.JButton UpdatebtnSiswa;
    private javax.swing.JButton UpdatebtnSpp;
    private javax.swing.JButton UpdatebtnTransaksi;
    private javax.swing.JTextField alamatSiswa;
    private javax.swing.JTextField bulanBayar;
    private javax.swing.JTextField idKelas;
    private javax.swing.JTextField idKelasSiswa;
    private javax.swing.JTextField idPetugas;
    private javax.swing.JTextField idPetugasTransaksi;
    private javax.swing.JTextField idSIswaTransaksi;
    private javax.swing.JTextField idSiswa;
    private javax.swing.JTextField idSpp;
    private javax.swing.JTextField idSppSiswa;
    private javax.swing.JTextField idSppTransaksi;
    private javax.swing.JTextField idTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jumlahBayar;
    private javax.swing.JTextField kompetensiKelas;
    private javax.swing.JTextField levelPetugas;
    private javax.swing.JTextField namaKelas;
    private javax.swing.JTextField namaPetugas;
    private javax.swing.JTextField namaSiswa;
    private javax.swing.JTextField nisSiswa;
    private javax.swing.JTextField noTelpSiswa;
    private javax.swing.JTextField nominalSpp;
    private javax.swing.JTable tableKelas;
    private javax.swing.JTable tableLaporan;
    private javax.swing.JTable tablePetugas;
    private javax.swing.JTable tableSiswa;
    private javax.swing.JTable tableSpp;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField tahunBayar;
    private javax.swing.JTextField tahunSpp;
    private javax.swing.JButton tambahDataTransaksi;
    private javax.swing.JButton tambahKelasbtn;
    private javax.swing.JButton tambahPetugasbtn;
    private javax.swing.JButton tambahSppbtn;
    private javax.swing.JTextField tanggalBayar;
    private javax.swing.JTextField usernamePetugas;
    private javax.swing.JLabel welcometxt;
    // End of variables declaration//GEN-END:variables
}
